apiVersion: apps/v1
kind: Deployment
metadata:
  name: sentiment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: sentiment-api
  template:
    metadata:
      labels:
        app: sentiment-api
    spec:
      containers:
      - name: sentiment-api
        image: thehungrypigeon/sentimentdetails
        resources:
          limits:
            memory: "256Mi"
            cpu: "250m"
        ports:
        - containerPort: 9000
        volumeMounts:
        - mountPath: ./results
          name: sentiment-volume
      volumes:
      - name: sentiment-volume
        hostPath:
          path: ./results
          type: DirectoryOrCreate
---

apiVersion: v1
kind: Service
metadata:
  name: sentiment-api-service
spec:
  selector:
    app: sentiment-api


  ports:
  - port: 9000
    targetPort: 9000
  type: LoadBalancer