name: Blah-Frontend

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    defaults:
      run:
        working-directory: ./

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: './blah-controller/package-lock.json'
        
    - run: npm ci
    - run: npm run build --if-present

    - name: Start minikube
      uses: medyagh/setup-minikube@master

    - uses: azure/setup-kubectl@v3
      id: install 

    - name: Run Playbook
      shell: bash
      run: ansible-playbook -i inventory ansible-playbook.yml 
